packages:
    - "packages/*"
    - "apps/*"
    - "infrastructure/*"

catalog:
    # Frameworks
    "@nuxt/fonts": 0.14.0
    "@nuxtjs/i18n": 10.5.0
    nuxt: ^4.5.0
    vue-tsc: ^3.3.0
    vue: ^3.5.38
    vite: ^8.0.16

    # TS
    typescript: ^6.0.3
    "@types/node": ^25.9.1

    # Testing
    vitest: ^4.1.7

    # Misc
    eslint: ^10.4.1

    # Infra
    hono: ^4.9.0
    "@hono/node-server": ^1.14.0
