import type { Capability, Doc, Kind } from "./capabilities.ts";
import { documentedBy } from "./capabilities.ts";

/** Leads are hard-wrapped here, not joined from a sentence: the output has to obey `house-docs`. */
const SECTIONS: { kind: Kind, heading: string, lead: string[] }[] = [
    {
        kind: "command",
        heading: "⌨️ Commands",
        lead: [
            "Root commands run against affected projects only. The per-project rows below them are the",
            "ones the root doesn't expose — `lint`, `typecheck`, `test` and `build` exist on every project",
            "and are documented once in the [root README](../README.md#-getting-started).",
        ],
    },
    {
        kind: "hook",
        heading: "🪝 Git hooks",
        lead: [
            "These run themselves, but only after `git config core.hooksPath .husky` — a fresh clone has no",
            "hooks at all until that is set.",
        ],
    },
    {
        kind: "workflow",
        heading: "⚙️ Workflows",
        lead: ["GitHub Actions, named as the Actions tab shows them rather than by filename."],
    },
    {
        kind: "skill",
        heading: "🛠 Agent skills",
        lead: [
            "Instructions an agent loads for one kind of task. Worth reading as a human too: a skill is the",
            "shortest statement of how a task is meant to go here.",
        ],
    },
];

/** Relative to `docs/FEATURES.md`, which sits one directory below the repo root. */
const link = (path: string): string => `[\`${path}\`](../${path})`;

const row = (capability: Capability, docs: Doc[]): string => {
    const explains = documentedBy(capability, docs);
    return `| \`${capability.invocation}\` | ${link(capability.source)} | ${explains ? link(explains) : "—"} |`;
};

const section = (
    { kind, heading, lead }: { kind: Kind, heading: string, lead: string[] },
    capabilities: Capability[],
    docs: Doc[],
): string[] => {
    const rows = capabilities.filter((capability) => capability.kind === kind);
    if (rows.length === 0) return [];

    return [
        `## ${heading}`,
        "",
        ...lead,
        "",
        "| Capability | Declared in | Explained in |",
        "| --- | --- | --- |",
        ...rows.map((capability) => row(capability, docs)),
        "",
    ];
};

/**
 * A `—` in the Explained-in column is the point of the file: it means a capability exists that no
 * doc mentions, which is how `commit-msg`'s subject rewriting and `packages/ui`'s Storybook stayed
 * invisible for as long as they did.
 */
export const render = (capabilities: Capability[], docs: Doc[]): string =>
    [
        "# 🗺 Features",
        "",
        "Every command, git hook, workflow and agent skill in this repo, with the doc that explains each",
        "one. Start here when you don't yet know what to go and read.",
        "",
        "**Generated by `pnpm docs:map` — do not edit.** It is an index and nothing more: the *why* lives",
        "in the doc each row points at, so there is no prose here that can drift from its source. A row",
        "with no doc is a real gap rather than a rendering artifact.",
        "",
        ...SECTIONS.flatMap((meta) => section(meta, capabilities, docs)),
    ].join("\n");
