name: CI

on:
    push:
        branches: [master]
    pull_request:

permissions:
    contents: read

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version-file: .nvmrc
                  cache: pnpm

            - run: pnpm install --frozen-lockfile --ignore-scripts

            - uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
              with:
                  main-branch-name: master

            - run: pnpm exec nx affected -t lint typecheck test build
